language: node_js
sudo: false
node_js:
  - "4.2.2"

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

env:
  - COVERALLS_SERVICE_NAME="travis-ci"
  - COVERALLS_REPO_TOKEN="sj8SOxUBGaVeFGSY9ryrC2eTFpVjCPHJl"

notifications:
  email:
    - videos5@corp.globo.com
  slack: globo:F1iVlyrzR4iX8OS7h8fwMcqx